CREATE TABLE stochastic_1 (
  run_id                                 integer,
  year                                   integer,
  country                                varchar(3),
  "cases_yf-no-vaccination"              double precision,
  "cases_yf-preventive-default"          double precision,
  "cases_yf-preventive-ia2030_target"    double precision,
  "cases_yf-routine-default"             double precision,
  "cases_yf-routine-ia2030_target"       double precision,
  "dalys_yf-no-vaccination"              double precision,
  "dalys_yf-preventive-default"          double precision,
  "dalys_yf-preventive-ia2030_target"    double precision,
  "dalys_yf-routine-default"             double precision,
  "dalys_yf-routine-ia2030_target"       double precision,
  "deaths_yf-no-vaccination"             double precision,
  "deaths_yf-preventive-default"         double precision,
  "deaths_yf-preventive-ia2030_target"   double precision,
  "deaths_yf-routine-default"            double precision,
  "deaths_yf-routine-ia2030_target"      double precision
);
