#!/usr/bin/env bash

read -p "Create volume?" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    docker volume create pgdata
fi

docker run --rm --name experiment \
  -p 5432:5432 \
  -v pgdata:/var/lib/postgresql/data \
  -v "${PWD}":/src \
  -e POSTGRES_PASSWORD=password \
  -d postgres -c config_file=/src/scripts/postgresql.conf
