## Note this doesn't work as a script - run interactively

montagu::montagu_server_global_default_set(
  montagu::montagu_server("production", "montagu.vaccineimpact.org"))

no_vac <- montagu::montagu_burden_estimate_sets("PSU-Ferrari", "202110gavi-3", "measles-no-vaccination")
campaign_default <- montagu::montagu_burden_estimate_sets("PSU-Ferrari", "202110gavi-3", "measles-campaign-default")
campaign_only_default <- montagu::montagu_burden_estimate_sets("PSU-Ferrari", "202110gavi-3", "measles-campaign-only-default")
mcv1 <- montagu::montagu_burden_estimate_sets("PSU-Ferrari", "202110gavi-3", "measles-mcv1-default")
mcv2 <- montagu::montagu_burden_estimate_sets("PSU-Ferrari", "202110gavi-3", "measles-mcv2-default")
campaign_ia <- montagu::montagu_burden_estimate_sets("PSU-Ferrari", "202110gavi-3", "measles-campaign-ia2030_target")
campaign_only_ia <- montagu::montagu_burden_estimate_sets("PSU-Ferrari", "202110gavi-3", "measles-campaign-only-ia2030_target")
mcv1_ia <- montagu::montagu_burden_estimate_sets("PSU-Ferrari", "202110gavi-3", "measles-mcv1-ia2030_target")
mcv2_ia <- montagu::montagu_burden_estimate_sets("PSU-Ferrari", "202110gavi-3", "measles-mcv2-ia2030_target")

data <- montagu::montagu_burden_estimate_set_data("PSU-Ferrari", "202110gavi-3", "measles-no-vaccination", max(no_vac$id))
dir.create("central", FALSE, FALSE)
write.csv(data, "central/PSU-Ferrari_measles-no-vaccination.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("PSU-Ferrari", "202110gavi-3", "measles-campaign-default", max(campaign_default$id))
write.csv(data, "central/PSU-Ferrari_measles-campaign-default.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("PSU-Ferrari", "202110gavi-3", "measles-campaign-only-default", max(campaign_only_default$id))
write.csv(data, "central/PSU-Ferrari_measles-campaign-only-default.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("PSU-Ferrari", "202110gavi-3", "measles-mcv1-default", max(mcv1$id))
write.csv(data, "central/PSU-Ferrari_measles-mcv1-default.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("PSU-Ferrari", "202110gavi-3", "measles-mcv2-default", max(mcv2$id))
write.csv(data, "central/PSU-Ferrari_measles-mcv2-default.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("PSU-Ferrari", "202110gavi-3", "measles-campaign-ia2030_target", max(campaign_ia$id))
write.csv(data, "central/PSU-Ferrari_measles-campaign-ia2030_target.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("PSU-Ferrari", "202110gavi-3", "measles-campaign-only-ia2030_target", max(campaign_only_ia$id))
write.csv(data, "central/PSU-Ferrari_measles-campaign-only-ia2030_target.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("PSU-Ferrari", "202110gavi-3", "measles-mcv1-ia2030_target", max(mcv1_ia$id))
write.csv(data, "central/PSU-Ferrari_measles-mcv1-ia2030_target.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("PSU-Ferrari", "202110gavi-3", "measles-mcv2-ia2030_target", max(mcv2_ia$id))
write.csv(data, "central/PSU-Ferrari_measles-mcv2-ia2030_target.csv", row.names = FALSE)


no_vac <- montagu::montagu_burden_estimate_sets("LSHTM-Jit", "202110gavi-3", "measles-no-vaccination")
campaign_default <- montagu::montagu_burden_estimate_sets("LSHTM-Jit", "202110gavi-3", "measles-campaign-default")
campaign_only_default <- montagu::montagu_burden_estimate_sets("LSHTM-Jit", "202110gavi-3", "measles-campaign-only-default")
mcv1 <- montagu::montagu_burden_estimate_sets("LSHTM-Jit", "202110gavi-3", "measles-mcv1-default")
mcv2 <- montagu::montagu_burden_estimate_sets("LSHTM-Jit", "202110gavi-3", "measles-mcv2-default")
campaign_ia <- montagu::montagu_burden_estimate_sets("LSHTM-Jit", "202110gavi-3", "measles-campaign-ia2030_target")
campaign_only_ia <- montagu::montagu_burden_estimate_sets("LSHTM-Jit", "202110gavi-3", "measles-campaign-only-ia2030_target")
mcv1_ia <- montagu::montagu_burden_estimate_sets("LSHTM-Jit", "202110gavi-3", "measles-mcv1-ia2030_target")
mcv2_ia <- montagu::montagu_burden_estimate_sets("LSHTM-Jit", "202110gavi-3", "measles-mcv2-ia2030_target")

data <- montagu::montagu_burden_estimate_set_data("LSHTM-Jit", "202110gavi-3", "measles-no-vaccination", max(no_vac$id))
dir.create("central", FALSE, FALSE)
write.csv(data, "central/LSHTM-Jit_measles-no-vaccination.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("LSHTM-Jit", "202110gavi-3", "measles-campaign-default", max(campaign_default$id))
write.csv(data, "central/LSHTM-Jit_measles-campaign-default.csv", row.names = FALSE)
## Manually set the ID for campaign-only-default scenario as later uploaded data is empty
data <- montagu::montagu_burden_estimate_set_data("LSHTM-Jit", "202110gavi-3", "measles-campaign-only-default", 2185)
write.csv(data, "central/LSHTM-Jit_measles-campaign-only-default.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("LSHTM-Jit", "202110gavi-3", "measles-mcv1-default", max(mcv1$id))
write.csv(data, "central/LSHTM-Jit_measles-mcv1-default.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("LSHTM-Jit", "202110gavi-3", "measles-mcv2-default", max(mcv2$id))
write.csv(data, "central/LSHTM-Jit_measles-mcv2-default.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("LSHTM-Jit", "202110gavi-3", "measles-campaign-ia2030_target", max(campaign_ia$id))
write.csv(data, "central/LSHTM-Jit_measles-campaign-ia2030_target.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("LSHTM-Jit", "202110gavi-3", "measles-campaign-only-ia2030_target", max(campaign_only_ia$id))
write.csv(data, "central/LSHTM-Jit_measles-campaign-only-ia2030_target.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("LSHTM-Jit", "202110gavi-3", "measles-mcv1-ia2030_target", max(mcv1_ia$id))
write.csv(data, "central/LSHTM-Jit_measles-mcv1-ia2030_target.csv", row.names = FALSE)
data <- montagu::montagu_burden_estimate_set_data("LSHTM-Jit", "202110gavi-3", "measles-mcv2-ia2030_target", max(mcv2_ia$id))
write.csv(data, "central/LSHTM-Jit_measles-mcv2-ia2030_target.csv", row.names = FALSE)
